<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Gotowy tekst</name>
  <uuid>ee5b0ca5-b9a5-4f36-a1a2-33544a71f778</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if GrupaKrwi is not null 
  then set decision to "Twój dawca jest  " + GrupaKrwi ;


	]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
