<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>MNO</name>
  <uuid>e058e2f9-95df-40cf-a7d3-9ec713cfafed</uuid>
  <documentation><![CDATA[aa]]></documentation>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to  ((dZLO + dWProj + dSTZAD + dSTR + dOpoz) / 5) * 100;
]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
