<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>ZGOD</name>
  <uuid>5d06e7d7-9fe9-480a-9b42-31984472545a</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	ZgodnoscStrategii is more than 5
then
	set decision to 1 ;
else set decision to 0.5;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
