<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>default-value-setting</name>
  <uuid>23a3316e-51f1-4eaf-aaa1-5c84d1877508</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set grupa_taryfowa to "G12" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
