<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>node_6_missing_rule_5</name>
  <uuid>6b8f84a5-d998-4805-89c6-0e31cbed6988</uuid>
  <documentation><![CDATA[Suggested missing rule: The decision needs to be reviewed.]]></documentation>
  <active>false</active>
  <locale>en_US</locale>
  <definition><![CDATA[if
	StopienZadowolenia is less than 2 
	and StopienZadowolenia is at least 1 
then
	-- This is a generated rule. Choose a meaningful value for the decision variable.
	set decision to 0 ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
