<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>node_6_missing_rule_1</name>
  <uuid>26e70d3a-2d52-40ce-9dda-1a3899450b87</uuid>
  <documentation><![CDATA[Suggested missing rule: The decision needs to be reviewed.]]></documentation>
  <active>false</active>
  <locale>en_US</locale>
  <definition><![CDATA[if
	StopienZadowolenia is at least 100 
then
	-- This is a generated rule. Choose a meaningful value for the decision variable.
	set decision to 0 ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
